export { default as HomeLayout } from "./HomeLayout";
export { default as Apod } from "./Apod";
export { default as Hubble } from "./Hubble";
export { default as Landing } from "./Landing";
export { default as News } from "./News";
export { default as SpaceX } from "./SpaceX";
export { default as Webb } from "./Webb";
export { default as SingleHubble } from "./SingleHubble";
export { default as ErrorMain } from "./ErrorMain";